### ISSUE TITLE
"Failed to Edit the Page" when editing some pages with images with front end editor

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/victron-press#10]
Some pages consistently give this error when editing and making changes.

https://docs.victronenergy.com/veconfigure.html

Sometimes the changes go through, other times they do not, and changes must be made in github.

![Screen Shot 2019-05-11 at 7 57 22 pm](https://user-images.githubusercontent.com/19315922/57573388-529bce80-7427-11e9-9963-628f30b294d2.jpg)

**Comment by lasselicht** [comment]
Adding duplicate images in the same commit generates this error. We will add a unique string to each filename to prevent this issue from happening. The short solution is to not upload the same image twice but to copy past the same url from the .md

**Comment by DvdGiessen** [comment]
We have reworked the commit logic in d1dd91c43c26f8967e8f52186c71881667cef3c3 to resolve the bug with duplicated images, which has resolved this issue.
