### ISSUE TITLE
BlueSolar PWM Pro communication protocol documentation!

### ISSUE THREAD

**Issue by mikegleasonjr** [victronenergy/victron-press#3]
I am sorry If I am in the wrong place to ask this but I already did in the community forums and got no answer...

Basically I want to know if you can publish the Modbus protocol used to communicate with the BlueSolar PWM Pro charge controller.

I would write an open source Prometheus exporter so that I can log the data and visualize them in Grafana.

Right now I don't have much access to a Windows machine and a full blown computer running Windows is too much for my array. Can't easily extract the data automatically either with the Windows program.

I know this is not your flagship product but I am a Canadian living in Morocco and we don't have access to a lot of products here, including the remote controller... This little charge controller is all I need and is awesome.

See my original question here: https://community.victronenergy.com/questions/15939/bluesolar-pwm-pro-serial-protocol.html

Thanks!

**Comment by mpvader** [comment]
Hi Mike, See answer in community.
