### ISSUE TITLE
Warning, danger and tip codes do not render in the front end preview

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/victron-press#5]
The coloured containers as described here - https://docs.victronenergy.com/markdown-cheatsheet.html#coloured-containers

 for 

::: warning
This is a warning you should know about.
:::

Do not show up in the in the front end editors preview render.

**Comment by lasselicht** [comment]
We are aware of this. We need to enable all the plugins that are active in Vuepress in the Toast UI Preview. This is planned for release 0.5.0
