### ISSUE TITLE
Prefixed to the commit description with the name of the file that has been edited

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/victron-press#6]
Please prefill the commit msg box with the file name and a colon and a space. So:

vedirect-lorawan.md: ....

As described here - https://victrondevelopment.slack.com/archives/CE316QP2Q/p1554821451033900?thread_ts=1554798977.029000&cid=CE316QP2Q

**Comment by lasselicht** [comment]
@Wholistic @mpvader and I have discussed this matter some time ago and decided not to add the prefixes.

**Comment by mpvader** [comment]
The reason was that there are better ways, to keep an overview of whats going on; for later
