### ISSUE TITLE
Export www-documentation repo from victronenergy org to victron-docs org

### ISSUE THREAD

**Issue by Wholistic** [victronenergy/victron-press#9]
This is a high priority:

- to allow others to assign additional editors to the docs.
- to reduce the content clutter in the Victronenergy dash, and leave it to real development.

The new org has already been created, but the docs need to be moved over there, and also the website needs to be pointed to the new location.

https://github.com/organizations/victron-docs

**Comment by lasselicht** [comment]
Hi @guy this is not a bug but a backlog item. It is in the current release and will be picked up in the next week.
